base_url = "https://blog.tom.sh"
title = "Francis Daily"
description = "Daily blog written by Francis"
compile_sass = false
build_search_index = false


[markdown]
highlight_code = true

[extra]
author = "Francis"
